FROM node:22.15.0-alpine3.21

RUN npm i -g pnpm
RUN npm i -g @nestjs/cli
RUN corepack enable

WORKDIR /work

COPY --chown=node:node . .

RUN corepack prepare pnpm@10.17.0 --activate
RUN pnpm install
RUN pnpm build

