version: '3'

services:
  #  node:
  #    build:
  #      context: .
  #      dockerfile: .docker/compose/nodejs/Dockerfile.dev
  #    container_name: nest_turbo_node
  #    extends:
  #      file: .docker/compose/nodejs/node.yml
  #      service: node
  #    ports:
  #      - '3300:3300'
  #      - '3301:3301'
  #    depends_on:
  #      - db
  #    networks:
  #      - nest-turbo-network
  #    env_file:
  #      - .env
  #    entrypoint: pnpm prod
  #
  #  migrate:
  #    build:
  #      context: .
  #      dockerfile: .docker/compose/nodejs/Dockerfile.dev
  #    container_name: nest_turbo_migrate_runner
  #    extends:
  #      file: .docker/compose/nodejs/node.yml
  #      service: node
  #    depends_on:
  #      - db
  #    networks:
  #      - nest-turbo-network
  #    env_file:
  #      - .env
  #    restart: "no"
  db:
    container_name: nest_turbo_user_db
    extends:
      file: .docker/compose/postgresql/postgresql.yml
      service: postgresql
    ports:
      - '5534:5432'
    volumes:
      - ${PWD}/.docker/volumes/user_pgdata:/var/lib/postgresql/data
    networks:
      - nest-turbo-network
    environment:
      POSTGRES_USER: ${DEFAULT_PG_USER}
      POSTGRES_PASSWORD: ${DEFAULT_PG_PASSWORD}
      POSTGRES_DB: ${DEFAULT_PG_DATABASE}
    env_file:
      - .env

  redis:
    container_name: nest_turbo_redis
    extends:
      file: .docker/compose/redis/redis.yml
      service: redis
    ports:
      - '6374:6379'
    networks:
      - nest-turbo-network
    volumes:
      - ${PWD}/.docker/volumes/redis_data:/data
    command: redis-server --appendonly yes --dir /data

  redisinsight:
    container_name: nest_turbo_redisinsight
    extends:
      file: .docker/compose/redis/redis.yml
      service: redisinsight
    depends_on:
      - redis
    volumes:
      - ${PWD}/.docker/volumes/redisinsight_data:/db
    ports:
      - '5544:5540'
    links:
      - redis
    networks:
      - nest-turbo-network

#  kafka:
#    container_name: nest_turbo_kafka
#    extends:
#      file: .docker/compose/kafka/kafka.yml
#      service: kafka
#    networks:
#      - nest-turbo-network
#    volumes:
#      - ${PWD}/.docker/volumes/kafka_data:/var/lib/kafka/data
#    ports:
#      - '9082:9092'
#      - '9086:9094'
#    environment:
#      KAFKA_CLUSTER_ID: '4b92c42d627c44e995f33f6756857945'
#      KAFKA_NODE_ID: 1
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
#      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,OUTSIDE://:9094
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:9086
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
#      KAFKAJS_NO_PARTITIONER_WARNING: 1
#
#  kafkaui:
#    container_name: nest_turbo_kafka_ui
#    extends:
#      file: .docker/compose/kafka/kafka.yml
#      service: kafka_ui
#    networks:
#      - nest-turbo-network
#    depends_on:
#      - kafka
#    ports:
#      - '18082:8080'
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
#      AUTH_TYPE: LOGIN_FORM
#      SPRING_SECURITY_USER_NAME: admin
#      SPRING_SECURITY_USER_PASSWORD: secret

volumes:
  redisinsight_data:
  kafka_data:
  kong_db_data:
  user_pgdata:
  redis_data:

networks:
  nest-turbo-network:
